"""baseline schema

Revision ID: 0f603005f247
Revises: 
Create Date: 2026-08-09 11:00:41.333486
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f603005f247'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adoption path: installations created before Alembic was wired up
    # already have the full schema (it was built by Base.metadata.create_all).
    # Re-creating those tables would fail, so the baseline is a no-op there
    # and later revisions carry on from this point.
    if sa.inspect(op.get_bind()).has_table("objects"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('name', sa.String(length=256), nullable=False, comment='Human-readable display name'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_profiles',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_profiles_object_id'), ['object_id'], unique=True)

    op.create_table('sensors',
    sa.Column('name', sa.String(length=256), nullable=False, comment='Human-readable display name'),
    sa.Column('mqtt_topic', sa.String(length=512), nullable=False, comment="MQTT topic exactly as entered by admin, e.g. 'frigo/intermarche/komora-a1'"),
    sa.Column('current_temperature', sa.Float(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_timeout_seconds', sa.Integer(), nullable=False, comment='Seconds without MQTT message before OFFLINE is detected'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_mqtt_topic'), ['mqtt_topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensors_object_id'), ['object_id'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('alarm_configs',
    sa.Column('alarm_type', sa.String(length=32), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('trigger_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarm_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarm_configs_sensor_id'), ['sensor_id'], unique=False)

    op.create_table('alarms',
    sa.Column('alarm_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger_value', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarms_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_sensor_id'), ['sensor_id'], unique=False)

    op.create_table('measurements',
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_sensor_id'), ['sensor_id'], unique=False)

    op.create_table('notification_endpoints',
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False, comment="Human-readable label, e.g. 'Manager phone'"),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['notification_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_endpoints_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_endpoints_profile_id'))

    op.drop_table('notification_endpoints')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_measurements_received_at'))

    op.drop_table('measurements')
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarms_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_alarms_object_id'))

    op.drop_table('alarms')
    with op.batch_alter_table('alarm_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarm_configs_sensor_id'))

    op.drop_table('alarm_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_object_id'))

    op.drop_table('users')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_object_id'))
        batch_op.drop_index(batch_op.f('ix_sensors_mqtt_topic'))

    op.drop_table('sensors')
    with op.batch_alter_table('notification_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_profiles_object_id'))

    op.drop_table('notification_profiles')
    op.drop_table('objects')
    # ### end Alembic commands ###
