<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useAlarmsStore } from "@/stores/alarms";
import { useObjectsStore } from "@/stores/objects";
const alarmsStore=useAlarmsStore(),objectsStore=useObjectsStore(),tab=ref<"active"|"history">("active");
const alarms=computed(()=>alarmsStore.alarms.filter(a=>tab.value==="active"?["triggered","pending","acknowledged"].includes(a.status):a.status==="resolved"));
const activeCount=computed(()=>alarmsStore.alarms.filter(a=>a.status==="triggered").length);
function object(id:string){return objectsStore.objects.find(x=>x.id===id)?.name||id.slice(0,8)} function type(x:string){return ({offline:"DEVICE OFFLINE",high_temperature:"HIGH TEMPERATURE",low_temperature:"LOW TEMPERATURE"} as Record<string,string>)[x]||x.replaceAll("_"," ").toUpperCase()} function date(x:string|null){return x?new Date(x).toLocaleString("pl-PL"):"N/A"} function duration(x:string){const h=Math.max(0,Math.floor((Date.now()-new Date(x).getTime())/3600000));return `${h}h ${Math.floor((Date.now()-new Date(x).getTime())/60000)%60}m`}
async function resetAll(){for(const a of alarms.value.filter(x=>x.status==="triggered"))await alarmsStore.acknowledgeAlarm(a.id)}
onMounted(()=>{alarmsStore.fetchAlarms();objectsStore.fetchObjects()});
</script>
<template><section class="alarms-page"><header><h1>Alarms</h1><p>Active alarms and alarm history.</p><div class="tabs"><button :class="{active:tab==='active'}" @click="tab='active'">Active Alarms <i>{{activeCount}}</i></button><button :class="{active:tab==='history'}" @click="tab='history'">History</button></div></header><div class="table-toolbar"><button v-if="tab==='active'" @click="resetAll">RESET ALL ({{activeCount}})</button></div><div v-if="alarmsStore.loading" class="empty">Loading…</div><div v-else-if="!alarms.length" class="empty">No alarms</div><div v-else class="alarm-table"><div class="tr th"><span>OBIEKT</span><span>SENSOR</span><span>ALARM TYPE</span><span>ACTIVE SINCE</span><span>DURATION</span><span>STATUS</span><span>ACTIONS</span></div><div v-for="alarm in alarms" :key="alarm.id" class="tr"><strong>{{object(alarm.object_id)}}</strong><b>{{alarm.sensor_id||'N/A'}}</b><span><i class="type">{{type(alarm.alarm_type)}}</i></span><time>{{date(alarm.triggered_at||alarm.detected_at)}}</time><time>{{duration(alarm.triggered_at||alarm.detected_at)}}</time><span><i :class="['status',alarm.status]">{{alarm.status==='triggered'?'ACTIVE':alarm.status.toUpperCase()}}</i></span><span><button v-if="alarm.status==='triggered'" class="reset" @click="alarmsStore.acknowledgeAlarm(alarm.id)">RESET</button></span></div></div></section></template>
<style scoped>
.alarms-page{min-height:calc(100vh - 157px);padding:18px 14px;background:#030509;color:#e4e9f2}.alarms-page header{border-bottom:1px solid #1d2530;padding-bottom:6px}.alarms-page h1{font-size:21px;margin:0 0 3px}.alarms-page p{margin:0;color:#9da9ba;font-size:13px}.tabs{display:flex;gap:10px;margin-top:23px}.tabs button{border:0;background:transparent;color:#99a5b5;font-size:13px;padding:9px 14px;border-radius:7px}.tabs .active{background:#42c9da;border:1px solid #b2e7eb;color:#07111c}.tabs i{font-style:normal;color:#b86a78;background:#e6a3ad88;border-radius:8px;padding:1px 6px;margin-left:8px}.table-toolbar{height:66px;display:flex;align-items:center;justify-content:flex-end}.table-toolbar button,.reset{background:#2b2210;color:#e2ae3f;border:1px solid #6d5422;border-radius:8px;padding:9px 15px;font-size:12px}.alarm-table{border:1px solid #1a2735;border-radius:10px;overflow:hidden;background:#171f2a}.tr{display:grid;grid-template-columns:14% 25% 17% 16% 10% 9% 9%;align-items:center;min-height:45px;padding:0 21px;color:#cbd3e0;font-size:13px;border-top:1px solid #1d2a38}.th{min-height:37px;border-top:0;color:#aeb8c9;font-size:11px;font-weight:600}.tr strong{font-size:14px;color:#fff}.tr b{font-size:13px}.tr time{color:#aab6c9}.type{font-style:normal;color:#ff717a;background:#5b2b34;border:1px solid #95505b;border-radius:12px;padding:5px 9px;font-size:10px;white-space:nowrap}.status{font-style:normal;color:#aebbd1;border:1px solid #354354;border-radius:12px;padding:5px 9px;font-size:10px}.status.triggered{color:#ff787f;border-color:#94404a;background:#4d2930}.reset{padding:5px 12px;font-size:10px}.empty{text-align:center;color:#8fa0b6;padding:50px}@media(max-width:800px){.tr{min-width:800px}.alarm-table{overflow:auto}.alarms-page{padding:15px}.table-toolbar{height:55px}}
</style>
